#!/bin/bash
STR="7-file"
echo -e "#!/bin/bash">>$STR;
echo echo "Best School" > '\*\\'\''"Best School"\'\''\\*$\?\*\*\*\*\*:)'>>$STR;
chmod a+x $STR;
git add *
git commit -m "added file 7 for task 7"
git push
