#!/bin/bash
STR="12-combinations"
echo -e "#!/bin/bash">>$STR;
echo 'echo {a..z}{a..z} | tr " " "\n" | grep -v "oo"'>>$STR;
chmod a+x $STR;
git add *
git commit -m "added file 12 for task 12"
git push
